export default data = [
    { label: "AED", value: "United Arab Emirates Dirham" },
    { label: "AFN", value: "Afghan Afghani" },
    { label: "ALL", value: "Albanian Lek" },
    { label: "AMD", value: "Armenian Dram" },
    { label: "ANG", value: "Netherlands Antillean Guilder" },
    { label: "AOA", value: "Angolan Kwanza" },
    { label: "ARS", value: "Argentine Peso" },
    { label: "AUD", value: "Australian Dollar" },
    { label: "AWG", value: "Aruban Florin" },
    { label: "AZN", value: "Azerbaijani Manat" },
    { label: "BAM", value: "Bosnia-Herzegovina Convertible Mark" },
    { label: "BBD", value: "Barbadian Dollar" },
    { label: "BDT", value: "Bangladeshi Taka" },
    { label: "BGN", value: "Bulgarian Lev" },
    { label: "BHD", value: "Bahraini Dinar" },
    { label: "BIF", value: "Burundian Franc" },
    { label: "BMD", value: "Bermudan Dollar" },
    { label: "BND", value: "Brunei Dollar" },
    { label: "BOB", value: "Bolivian Boliviano" },
    { label: "BRL", value: "Brazilian Real" },
    { label: "BSD", value: "Bahamian Dollar" },
    { label: "BTC", value: "Bitcoin" },
    { label: "BTN", value: "Bhutanese Ngultrum" },
    { label: "BWP", value: "Botswanan Pula" },
    { label: "BYN", value: "New Belarusian Ruble" },
    { label: "BYR", value: "Belarusian Ruble" },
    { label: "BZD", value: "Belize Dollar" },
    { label: "CAD", value: "Canadian Dollar" },
    { label: "CDF", value: "Congolese Franc" },
    { label: "CHF", value: "Swiss Franc" },
    { label: "CLF", value: "Chilean Unit of Account (UF)" },
    { label: "CLP", value: "Chilean Peso" },
    { label: "CNY", value: "Chinese Yuan" },
    { label: "COP", value: "Colombian Peso" },
    { label: "CRC", value: "Costa Rican Colón" },
    { label: "CUC", value: "Cuban Convertible Peso" },
    { label: "CUP", value: "Cuban Peso" },
    { label: "CVE", value: "Cape Verdean Escudo" },
    { label: "CZK", value: "Czech Republic Koruna" },
    { label: "DJF", value: "Djiboutian Franc" },
    { label: "DKK", value: "Danish Krone" },
    { label: "DOP", value: "Dominican Peso" },
    { label: "DZD", value: "Algerian Dinar" },
    { label: "EGP", value: "Egyptian Pound" },
    { label: "ERN", value: "Eritrean Nakfa" },
    { label: "ETB", value: "Ethiopian Birr" },
    { label: "EUR", value: "Euro" },
    { label: "FJD", value: "Fijian Dollar" },
    { label: "FKP", value: "Falkland Islands Pound" },
    { label: "GBP", value: "British Pound Sterling" },
    { label: "GEL", value: "Georgian Lari" },
    { label: "GGP", value: "Guernsey Pound" },
    { label: "GHS", value: "Ghanaian Cedi" },
    { label: "GIP", value: "Gibraltar Pound" },
    { label: "GMD", value: "Gambian Dalasi" },
    { label: "GNF", value: "Guinean Franc" },
    { label: "GTQ", value: "Guatemalan Quetzal" },
    { label: "GYD", value: "Guyanaese Dollar" },
    { label: "HKD", value: "Hong Kong Dollar" },
    { label: "HNL", value: "Honduran Lempira" },
    { label: "HRK", value: "Croatian Kuna" },
    { label: "HTG", value: "Haitian Gourde" },
    { label: "HUF", value: "Hungarian Forint" },
    { label: "IDR", value: "Indonesian Rupiah" },
    { label: "ILS", value: "Israeli New Sheqel" },
    { label: "IMP", value: "Manx pound" },
    { label: "INR", value: "Indian Rupee" },
    { label: "IQD", value: "Iraqi Dinar" },
    { label: "IRR", value: "Iranian Rial" },
    { label: "ISK", value: "Icelandic Króna" },
    { label: "JEP", value: "Jersey Pound" },
    { label: "JMD", value: "Jamaican Dollar" },
    { label: "JOD", value: "Jordanian Dinar" },
    { label: "JPY", value: "Japanese Yen" },
    { label: "KES", value: "Kenyan Shilling" },
    { label: "KGS", value: "Kyrgystani Som" },
    { label: "KHR", value: "Cambodian Riel" },
    { label: "KMF", value: "Comorian Franc" },
    { label: "KPW", value: "North Korean Won" },
    { label: "KRW", value: "South Korean Won" },
    { label: "KWD", value: "Kuwaiti Dinar" },
    { label: "KYD", value: "Cayman Islands Dollar" },
    { label: "KZT", value: "Kazakhstani Tenge" },
    { label: "LAK", value: "Laotian Kip" },
    { label: "LBP", value: "Lebanese Pound" },
    { label: "LKR", value: "Sri Lankan Rupee" },
    { label: "LRD", value: "Liberian Dollar" },
    { label: "LSL", value: "Lesotho Loti" },
    { label: "LTL", value: "Lithuanian Litas" },
    { label: "LVL", value: "Latvian Lats" },
    { label: "LYD", value: "Libyan Dinar" },
    { label: "MAD", value: "Moroccan Dirham" },
    { label: "MDL", value: "Moldovan Leu" },
    { label: "MGA", value: "Malagasy Ariary" },
    { label: "MKD", value: "Macedonian Denar" },
    { label: "MMK", value: "Myanma Kyat" },
    { label: "MNT", value: "Mongolian Tugrik" },
    { label: "MOP", value: "Macanese Pataca" },
    { label: "MRO", value: "Mauritanian Ouguiya" },
    { label: "MUR", value: "Mauritian Rupee" },
  ];